CREATE TABLE USERS (
    ID BIGINT IDENTITY(1,1),
    USERNAME VARCHAR(50) UNIQUE NOT NULL,
    EMAIL VARCHAR(100) UNIQUE NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    ROLE VARCHAR(20) NOT NULL,
    CREATED_AT DATETIME DEFAULT GETDATE(),
    CONSTRAINT PK_USER PRIMARY KEY(ID)
);
