CREATE TABLE ROLES (
    ID INT IDENTITY(1,1),
    ROLE_NAME VARCHAR(20) UNIQUE NOT NULL,
    CONSTRAINT PK_ROLE PRIMARY KEY(ID)
);

INSERT INTO ROLES (ROLE_NAME) VALUES ('Farmer'), ('Tractor Owner'), ('Admin');
