-- Create table Farmer

CREATE TABLE FARMER (
    ID INT IDENTITY(1,1) NOT NULL,
    NAME VARCHAR(100) NOT NULL,
    CONTACT VARCHAR(15) NOT NULL,
    AGE INT,
    ADDRESS TEXT,
    EMAIL VARCHAR(100),
    LAND_AREA DECIMAL(10, 2),
    CROPS_GROWN TEXT,
    TRACTOR_OWNED BIT DEFAULT 0,
    REGISTRATION_DATE DATE DEFAULT GETDATE(),
    AADHAR_NUMBER VARCHAR(12),
    PAYMENT_DUE DECIMAL(10, 2) DEFAULT 0.00,
    CONSTRAINT PK01_FARMER PRIMARY KEY (ID)
);
