CREATE TABLE FARMERS (
    ID BIGINT IDENTITY(1,1),
    NAME VARCHAR(255) NOT NULL,
    CONSTRAINT PK_FARMERS PRIMARY KEY(ID),
    CONSTRAINT UK_FARMERS UNIQUE(NAME)
);

CREATE TABLE TRACTOR_OWNER_TASKS (
    ID BIGINT IDENTITY(1,1),
    TRACTOR_OWNER_ID BIGINT NOT NULL,
    TASK_NAME VARCHAR(255) NOT NULL,
    PRICE DECIMAL(10,2) NOT NULL,
    CONSTRAINT PK_TRACTOR_OWNER_TASKS PRIMARY KEY(ID),
    CONSTRAINT FK01_USER_TRACTOR_OWNER FOREIGN KEY (TRACTOR_OWNER_ID) REFERENCES USERS(ID),
    CONSTRAINT UK_TRACTOR_OWNER_TASKS UNIQUE (TRACTOR_OWNER_ID, TASK_NAME)
);

CREATE TABLE WORK_LOGS (
    ID BIGINT IDENTITY(1,1),
    FARMER_ID BIGINT NOT NULL,
    TRACTOR_OWNER_TASK_ID BIGINT NOT NULL,
    TASK_DATE DATE NOT NULL,
    AMOUNT_PAID DECIMAL(10,2) NOT NULL,
    CONSTRAINT PK_WORK_LOGS PRIMARY KEY(ID),
    CONSTRAINT FK01_FARMERS FOREIGN KEY (FARMER_ID) REFERENCES FARMERS(ID),
    CONSTRAINT FK02_TRACTOR_OWNER_TASKS FOREIGN KEY (TRACTOR_OWNER_TASK_ID) REFERENCES TRACTOR_OWNER_TASKS(ID)
);
