CREATE TABLE USER_DETAILS (
    ID BIGINT IDENTITY(1,1),
    USER_ID BIGINT NOT NULL,
    FULL_NAME VARCHAR(255) NOT NULL,
    PHONE_NUMBER VARCHAR(15) NOT NULL,
    ADDRESS TEXT,
    CONSTRAINT PK_USER_DETAILS PRIMARY KEY(ID),
    CONSTRAINT UK_USER_DETAILS UNIQUE (USER_ID, PHONE_NUMBER),
    CONSTRAINT FK01_USER_ID_USER FOREIGN KEY (USER_ID) REFERENCES USERS(ID)
);

CREATE TABLE FARMER_DETAILS (
    ID BIGINT IDENTITY(1,1),
    USER_DETAILS_ID BIGINT NOT NULL,
    LAND_OWNED DECIMAL(10,2) NOT NULL,
    CROP_TYPE VARCHAR(100) NOT NULL,
    WATER_SOURCE VARCHAR(100),
    CONSTRAINT PK_FARMER_DETAILS PRIMARY KEY(ID),
    CONSTRAINT UK_FARMER_DETAILS UNIQUE(USER_DETAILS_ID),
    CONSTRAINT FK01_USER_DETAILS_ID_USER_DETAILS1 FOREIGN KEY (USER_DETAILS_ID) REFERENCES USER_DETAILS(ID)
);

CREATE TABLE TRACTOR_OWNER_DETAILS (
    ID BIGINT IDENTITY(1,1),
    USER_DETAILS_ID BIGINT NOT NULL,
    TRACTOR_COUNT INT NOT NULL,
    TRACTOR_MODELS TEXT,
    RENTAL_PRICE_PER_HOUR DECIMAL(10,2) NOT NULL,
    AVAILABILITY_STATUS BIT DEFAULT 1,
    CONSTRAINT PK_TRACTOR_OWNER_DETAILS PRIMARY KEY(ID),
    CONSTRAINT UK_TRACTOR_OWNER_DETAILS UNIQUE(USER_DETAILS_ID),
    CONSTRAINT FK01_USER_DETAILS_ID_USER_DETAILS2 FOREIGN KEY (USER_DETAILS_ID) REFERENCES USER_DETAILS(ID)
);

ALTER TABLE USERS DROP COLUMN ROLE;

ALTER TABLE USERS ADD ROLE_ID INT NOT NULL;

ALTER TABLE USERS ADD CONSTRAINT FK01_ROLE_ID_ROLE FOREIGN KEY (ROLE_ID) REFERENCES ROLES(ID);
